name: Coordinator

on:
  push:
    branches:
      - main
      - staging
    paths:
      - 'coordinator/**'
      - '.github/workflows/coordinator.yml'
  pull_request:
    branches:
      - main
      - staging
    paths:
      - 'coordinator/**'
      - '.github/workflows/coordinator.yml'

defaults:
  run:
    working-directory: 'coordinator'

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly-2022-08-23
        override: true
        components: rustfmt, clippy
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18.x
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Lint
      run: |
        rm -rf $HOME/.cache/golangci-lint
        make lint
    - name: copy cargo lock file for cache
      run: cp ../common/zkp/rust/Cargo.lock .
    - name: Cache cargo registry
      uses: actions/cache@v2
      with:
        path: ~/.cargo/registry
        key: ${{ runner.os }}-registry-${{ hashFiles('./Cargo.lock') }}
    - name: Cache cargo index
      uses: actions/cache@v2
      with:
        path: ~/.cargo/git
        key: ${{ runner.os }}-index-${{ hashFiles('./Cargo.lock') }}
    - name: Cache cargo target
      uses: actions/cache@v2
      with:
        path: /home/runner/work/scroll/scroll/common/zkp/rust/target
        key: ${{ runner.os }}-target-${{ hashFiles('./Cargo.lock') }}
    - name: Test
      run: |
        make coordinator 
        go test -v ./...
  goimports-lint:
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18.x
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install goimports
      run: go install golang.org/x/tools/cmd/goimports
    - run: goimports -local scroll-tech/coordinator/ -w .
    - run: go mod tidy
    # If there are any diffs from goimports or go mod tidy, fail.
    - name: Verify no changes from goimports and go mod tidy
      run: |
        if [ -n "$(git status --porcelain)" ]; then
          exit 1
        fi
