name: Rollup

on:
  push:
    branches:
      - main
      - staging
      - develop
      - alpha
    paths:
      - 'rollup/**'
      - 'common/**'
      - '!common/version/version.go'
      - 'database/**'
      - '.github/workflows/rollup.yml'
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
    paths:
      - 'rollup/**'
      - 'common/**'
      - '!common/version/version.go'
      - 'database/**'
      - '.github/workflows/rollup.yml'

jobs:
  check:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.21.x
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install Solc
      uses: supplypike/setup-bin@v3
      with:
        uri: 'https://github.com/ethereum/solidity/releases/download/v0.8.24/solc-static-linux'
        name: 'solc'
        version: '0.8.24'
    - name: Install Geth Tools
      uses: gacts/install-geth-tools@v1
    - name: Lint
      working-directory: 'rollup'
      run: |
        rm -rf $HOME/.cache/golangci-lint
        make mock_abi
        make lint
  goimports-lint:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.21.x
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install goimports
      run: go install golang.org/x/tools/cmd/goimports
    - name: Run goimports lint
      run: goimports -local scroll-tech/rollup/ -w .
      working-directory: 'rollup'
    - name: Run go mod tidy
      run: go mod tidy
      working-directory: 'rollup'
    # If there are any diffs from goimports or go mod tidy, fail.
    - name: Verify no changes from goimports and go mod tidy
      working-directory: 'rollup'
      run: |
        if [ -n "$(git status --porcelain)" ]; then
          exit 1
        fi
  tests:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.21.x
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install Solc
      uses: supplypike/setup-bin@v3
      with:
        uri: 'https://github.com/ethereum/solidity/releases/download/v0.8.24/solc-static-linux'
        name: 'solc'
        version: '0.8.24'
    - name: Install Geth Tools
      uses: gacts/install-geth-tools@v1
    - name: Build prerequisites
      run: |
        make dev_docker
        make -C rollup mock_abi
    - name: Build rollup binaries
      working-directory: 'rollup'
      run: |
        make rollup_bins
    - name: Test rollup packages
      working-directory: 'rollup'
      run: |
        go test -v -race -gcflags="-l" -ldflags="-s=false" -coverprofile=coverage.txt -covermode=atomic ./...
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      with:
        flags: rollup
  # docker-build:
  #   if: github.event.pull_request.draft == false
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: Checkout code
  #     uses: actions/checkout@v2
  #   - name: Set up Docker Buildx
  #     uses: docker/setup-buildx-action@v2
  #   - run: make docker
